import { Command } from 'commander';
import { asyncHandler, output, loadConfig, withService } from '@/cli/utils/shared.js';
import { existsSync, readFileSync, writeFileSync, chmodSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { isValidRiskLevel, VALID_RISK_LEVELS } from '../../core/predictive/risk-levels.js';
import type { RiskLevel } from '../../core/predictive/risk-levels.js';
import { runGates } from './autopilot-engine.js';

const HOOK_MARKER = 'projectmind-autopilot';

export function createAutopilotCommand(): Command {
  const cmd = new Command('autopilot').description(
    'Agent workflow enforcement: pre-commit quality gates and git hook installation',
  );

  cmd
    .command('pre-commit')
    .description('Quality gate for commits/CI: exits 1 when any check fails')
    .option('--min-genome <n>', 'Minimum genome score percent', '70')
    .option('--format <fmt>', 'Output: text|json', 'text')
    .option(
      '--impact-risk-threshold <level>',
      'Risk level to block (low|medium|high|critical)',
      'high',
    )
    .option('--skip-impact-check', 'Skip impact risk gate (useful for performance)', false)
    .option('--allow-breaking-api', 'Allow breaking API surface changes (bypasses Gate 5)', false)
    .action(
      asyncHandler(
        async (opts: {
          minGenome: string;
          format: string;
          impactRiskThreshold?: string;
          skipImpactCheck?: boolean;
          allowBreakingApi?: boolean;
        }) => {
          // Validate --impact-risk-threshold value before proceeding.
          const rawThreshold = opts.impactRiskThreshold || 'high';
          if (!isValidRiskLevel(rawThreshold)) {
            output.error(
              `Invalid --impact-risk-threshold value: "${rawThreshold}". ` +
                `Must be one of: ${VALID_RISK_LEVELS.join(', ')}.`,
            );
            process.exit(1);
            return;
          }
          const threshold: RiskLevel = rawThreshold;

          // withService initializes the DB layer that runGates' statements need.
          await withService(['debt'], async () => {
            const gates = await runGates(
              parseInt(opts.minGenome, 10),
              threshold,
              opts.skipImpactCheck || false,
              opts.allowBreakingApi || false,
            );
            const failed = gates.filter((g) => !g.passed);
            const allPassed = failed.length === 0;

            if (opts.format === 'json') {
              output.info(JSON.stringify({ ok: allPassed, gates }, null, 2));
            } else {
              output.section('🤖 ProjectMind Pre-Commit Gate');
              for (const g of gates) {
                output.kv(`${g.passed ? '✅' : '❌'} ${g.name}`, g.detail);
              }
              if (!allPassed) {
                output.error(
                  `Gate FAILED — ${failed.length} check(s) must pass before committing.`,
                );
              } else {
                output.success('All gates passed.');
              }
            }

            if (!allPassed) process.exit(1);
          });
        },
      ),
    );

  cmd
    .command('install-hooks')
    .description('Install a git pre-commit hook that enforces "pm autopilot pre-commit"')
    .option('--uninstall', 'Remove the ProjectMind hook instead')
    .action(
      asyncHandler(async (opts: { uninstall?: boolean }) => {
        const root = loadConfig().projectRoot;
        const hooksDir = join(root, '.git', 'hooks');
        const hookPath = join(hooksDir, 'pre-commit');

        if (opts.uninstall) {
          if (existsSync(hookPath)) {
            const content = readFileSync(hookPath, 'utf-8');
            if (content.includes(HOOK_MARKER)) {
              rmSync(hookPath);
              output.success('ProjectMind pre-commit hook removed.');
            } else {
              output.warn(
                'Existing pre-commit hook is not managed by ProjectMind — leaving it untouched.',
              );
            }
          } else {
            output.info('No pre-commit hook present.');
          }
          return;
        }

        const cliEntry = join(root, 'dist', 'cli.js').replace(/\\/g, '/');
        const script = [
          '#!/bin/sh',
          `# ${HOOK_MARKER} — auto-generated by "pm autopilot install-hooks"`,
          'exec node "' + cliEntry + '" autopilot pre-commit',
          '',
        ].join('\n');

        writeFileSync(hookPath, script);
        try {
          chmodSync(hookPath, 0o755);
        } catch {
          // Windows filesystems may ignore chmod — git still executes the hook.
        }
        output.success(`✓ Pre-commit hook installed at ${hookPath}`);
        output.kv(
          'Gate',
          'pm autopilot pre-commit (high-debt, cycles, genome threshold, API surface)',
        );
        output.info('Use --uninstall to remove.');
      }),
    );

  return cmd;
}
