import { reportSuppressedError } from '../../utils/errors.js';
import { Command } from 'commander';
import { asyncHandler, output, loadConfig, withService } from '@/cli/utils/shared.js';
import { existsSync, readFileSync, writeFileSync, chmodSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { currentModuleDir } from '@/cli/utils/version.js';
import { isValidRiskLevel, VALID_RISK_LEVELS } from '../../core/predictive/risk-levels.js';
import type { RiskLevel } from '../../core/predictive/risk-levels.js';
import { runGates } from './autopilot-engine.js';
import { assertProjectPath } from '../../core/security/path-security.js';

const HOOK_MARKER = 'projectmind-autopilot';

/** Quote one value for a POSIX shell script (including Git Bash on Windows). */
export function quotePosixShellArg(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

/** Build the generated hook without interpolating a path into shell syntax. */
export function buildAutopilotHookScript(
  cliEntry: string,
  nodeExecutable: string = process.execPath,
): string {
  return [
    '#!/bin/sh',
    `# ${HOOK_MARKER} — auto-generated by "pm autopilot install-hooks"`,
    `exec ${quotePosixShellArg(nodeExecutable)} ${quotePosixShellArg(cliEntry)} autopilot pre-commit`,
    '',
  ].join('\n');
}

/** Keep Git's configured hooksPath inside the trusted project root. */
export function resolveGitHooksDirectory(gitHooksPath: string, projectRoot: string): string {
  const candidate = gitHooksPath.trim();
  if (!candidate) throw new Error('Git returned an empty hooks directory.');
  return assertProjectPath(candidate, projectRoot, { allowDirectory: true });
}

export function createAutopilotCommand(): Command {
  const cmd = new Command('autopilot').description(
    'Agent workflow enforcement: pre-commit quality gates and git hook installation',
  );

  cmd.action(() => {
    cmd.outputHelp();
  });

  cmd
    .command('pre-commit')
    .description('Quality gate for commits/CI: exits 1 when any check fails')
    .option('--min-genome <n>', 'Minimum genome score percent', '70')
    .option('--format <fmt>', 'Output: text|json', 'text')
    .option(
      '--impact-risk-threshold <level>',
      'Risk level to block (low|medium|high|critical)',
      'high',
    )
    .option('--skip-impact-check', 'Skip impact risk gate (useful for performance)', false)
    .option('--allow-breaking-api', 'Allow breaking API surface changes (bypasses Gate 5)', false)
    .action(
      asyncHandler(
        async (opts: {
          minGenome: string;
          format: string;
          impactRiskThreshold?: string;
          skipImpactCheck?: boolean;
          allowBreakingApi?: boolean;
        }) => {
          if (!['text', 'json'].includes(opts.format)) {
            throw new Error(`--format must be text or json: ${opts.format}`);
          }
          const minGenome = Number.parseFloat(opts.minGenome);
          if (!Number.isFinite(minGenome) || minGenome < 0 || minGenome > 100) {
            throw new Error(`--min-genome must be a number between 0 and 100: ${opts.minGenome}`);
          }
          // Validate --impact-risk-threshold value before proceeding.
          const rawThreshold = opts.impactRiskThreshold || 'high';
          if (!isValidRiskLevel(rawThreshold)) {
            output.error(
              `Invalid --impact-risk-threshold value: "${rawThreshold}". ` +
                `Must be one of: ${VALID_RISK_LEVELS.join(', ')}.`,
            );
            process.exitCode = 1;
            return;
          }
          const threshold: RiskLevel = rawThreshold;

          // withService initializes the DB layer that runGates' statements need.
          await withService(['debt'], async () => {
            const gates = await runGates(
              minGenome,
              threshold,
              opts.skipImpactCheck || false,
              opts.allowBreakingApi || false,
            );
            const failed = gates.filter((g) => !g.passed);
            const allPassed = failed.length === 0;

            if (opts.format === 'json') {
              output.json({ ok: allPassed, gates });
            } else {
              output.section('🤖 ProjectMind Pre-Commit Gate');
              for (const g of gates) {
                output.kv(`${g.passed ? '✅' : '❌'} ${g.name}`, g.detail);
              }
              if (!allPassed) {
                output.error(
                  `Gate FAILED — ${failed.length} check(s) must pass before committing.`,
                );
              } else {
                output.success('All gates passed.');
              }
            }

            // Set the exit code after withService has completed so its
            // database/cache cleanup always runs on both Windows and POSIX.
            if (!allPassed) process.exitCode = 1;
          });
        },
      ),
    );

  cmd
    .command('install-hooks')
    .description('Install a git pre-commit hook that enforces "pm autopilot pre-commit"')
    .option('--uninstall', 'Remove the ProjectMind hook instead')
    .action(
      asyncHandler(async (opts: { uninstall?: boolean }) => {
        const root = loadConfig().projectRoot;
        let gitHooksPath: string;
        try {
          gitHooksPath = execFileSync('git', ['rev-parse', '--git-path', 'hooks'], {
            cwd: root,
            encoding: 'utf8',
          }).trim();
        } catch {
          throw new Error(`Not a Git repository: ${root}`);
        }
        let hooksDir: string;
        try {
          hooksDir = resolveGitHooksDirectory(gitHooksPath, root);
        } catch (error) {
          throw new Error(
            `Git hooks directory is outside the project root: ${error instanceof Error ? error.message : String(error)}`,
          );
        }
        const hookPath = assertProjectPath(join(hooksDir, 'pre-commit'), root);

        if (opts.uninstall) {
          if (existsSync(hookPath)) {
            const content = readFileSync(hookPath, 'utf-8');
            if (content.includes(HOOK_MARKER)) {
              rmSync(hookPath);
              output.success('ProjectMind pre-commit hook removed.');
            } else {
              output.warn(
                'Existing pre-commit hook is not managed by ProjectMind — leaving it untouched.',
              );
            }
          } else {
            output.info('No pre-commit hook present.');
          }
          return;
        }

        const cliEntry = join(currentModuleDir(import.meta.url), '..', '..', 'cli.js').replace(
          /\\/g,
          '/',
        );
        const script = buildAutopilotHookScript(cliEntry);

        writeFileSync(hookPath, script);
        try {
          chmodSync(hookPath, 0o755);
        } catch (error) {
          reportSuppressedError(error, 'Intentional fallback src/cli/commands/autopilot.ts:158');
          // Windows filesystems may ignore chmod — git still executes the hook.
        }
        output.success(`Pre-commit hook installed at ${hookPath}`);
        output.kv(
          'Gate',
          'pm autopilot pre-commit (high-debt, cycles, genome threshold, API surface)',
        );
        output.info('Use --uninstall to remove.');
      }),
    );

  return cmd;
}
