import { Command } from 'commander';
import { withService, asyncHandler, output, logger } from '@/cli/utils/shared.js';
import { loadConfig } from '@/cli/utils/shared.js';
import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join, dirname } from '@/cli/utils/shared.js';

interface DocgenReport {
  modules: Array<{ path: string; fileCount: number }>;
  languages: Record<string, { files: number }>;
}

export function createDocgenCommand(): Command {
  const docgenCmd = new Command('docgen')
    .description('Generate documentation from code')
    .option('-f, --format <fmt>', 'Output: markdown|html', 'markdown')
    .option('-o, --output <dir>', 'Output directory', 'docs')
    .option('--api', 'Generate API reference')
    .action(asyncHandler(async (opts: { format: string; output: string; api: boolean }) => {
      await withService(['scale'], async (_ctx, services) => {
        const scale = services.scale!;
        const config = loadConfig();
        
        output.section('Documentation Generation');
        
        const report = scale.getScaleReport();
        const allFiles = report.modules.flatMap(m => m.files || []);
        const tsFiles = allFiles.filter(f => f.language === 'typescript');
        
        if (!opts.api) {
          output.info('Use --api to generate API reference');
          return;
        }
        
        const outputDir = join(config.projectRoot, opts.output);
        if (!existsSync(outputDir)) {
          mkdirSync(outputDir, { recursive: true });
        }
        
        let generated = 0;
        
        for (const file of tsFiles.slice(0, 20)) {
          try {
            const content = readFileSync(file.path, 'utf-8');
            
            const exports = extractExports(content);
            if (exports.length === 0) continue;
            
            const doc = generateFileDoc(file.relativePath, exports, content);
            const outPath = join(config.projectRoot, opts.output, file.relativePath.replace(/\.ts$/, '.md'));
            const outDir = dirname(outPath);
            if (!existsSync(outDir)) {
              mkdirSync(outDir, { recursive: true });
            }
            
            writeFileSync(outPath, doc);
            generated++;
          } catch {
            logger.debug(`Failed to generate doc for file, skipping`);
          }
        }
        
        output.success(`Generated ${generated} API docs in ${opts.output}/`);
        
        // Generate index
        const indexPath = join(config.projectRoot, opts.output, 'index.md');
        writeFileSync(indexPath, generateIndex(report));
        output.success(`Index written to ${opts.output}/index.md`);
      });
    }));

  docgenCmd
    .command('readme')
    .description('Generate README.md from project info')
    .option('-o, --output <file>', 'Output file', 'README.md')
    .action(asyncHandler(async (opts: { output: string }) => {
      await withService(['scale'], async (_ctx, services) => {
        const scale = services.scale!;
        const config = loadConfig();
        const report = scale.getScaleReport();
        
        const outputPath = join(config.projectRoot, opts.output);
        
        const languagesStr = Object.entries(report.languages).map(([k, v]) => `${k} (${(v as { files: number }).files})`).join(', ');
        
        const readme = `# ProjectMind Project

Living Codebase Intelligence Layer for AI Agents

## Project Statistics

- **Files:** ${report.totalFiles}
- **Lines of Code:** ${report.totalLines}
- **Languages:** ${languagesStr}
- **Agent Coverage:** ${(report.agentCoverage * 100).toFixed(1)}%
- **Avg Cognitive Load:** ${report.avgCognitiveLoad.toFixed(3)}

## Quick Start

\`\`\`bash
npm install
npm run build
projectmind scan
projectmind health
\`\`\`

## Commands

\`\`\`
projectmind scan          # Build knowledge graph
projectmind health        # System health check
projectmind genome        # Coherence genome score
projectmind debt          # Cognitive debt report
projectmind agent status  # Agent sessions
\`\`\`

---

*Generated by ProjectMind on ${new Date().toISOString().split('T')[0]}*
`;
        
        writeFileSync(outputPath, readme);
        output.success(`README written to ${opts.output}`);
      });
    }));

  return docgenCmd;
}

function extractExports(content: string): Array<{ name: string; type: string; params: string; doc?: string }> {
  const exports: Array<{ name: string; type: string; params: string; doc?: string }> = [];
  
  const funcRegex = /(?:^\s*\/\*\*[\s\S]*?\*\/\s*)?export\s+(?:async\s+)?function\s+(\w+)\s*\(([^)]*)\)/gm;
  let match;
  while ((match = funcRegex.exec(content)) !== null) {
    exports.push({ name: match[1], type: 'function', params: match[2], doc: match[0].includes('/**') ? match[0].match(/\*\*([\s\S]*?)\*\//)?.[1].trim() : undefined });
  }
  
  const classRegex = /export\s+class\s+(\w+)/g;
  while ((match = classRegex.exec(content)) !== null) {
    exports.push({ name: match[1], type: 'class', params: '' });
  }
  
  const interfaceRegex = /export\s+interface\s+(\w+)/g;
  while ((match = interfaceRegex.exec(content)) !== null) {
    exports.push({ name: match[1], type: 'interface', params: '' });
  }
  
  return exports;
}

function generateFileDoc(relPath: string, exports: Array<{ name: string; type: string; params: string; doc?: string }>, _content: string): string {
  const lines = [
    `# ${relPath}`,
    '',
    `**Language:** TypeScript`,
    `**Exports:** ${exports.length}`,
    '',
  ];
  
  for (const exp of exports) {
    lines.push(`## ${exp.type}: \`${exp.name}\``);
    if (exp.doc) {
      lines.push('', exp.doc, '');
    }
    if (exp.type === 'function') {
      lines.push(`\`\`\`typescript`, `export function ${exp.name}(${exp.params})`, `\`\`\``, '');
    } else if (exp.type === 'class') {
      lines.push(`\`\`\`typescript`, `export class ${exp.name}`, `\`\`\``, '');
    } else if (exp.type === 'interface') {
      lines.push(`\`\`\`typescript`, `export interface ${exp.name}`, `\`\`\``, '');
    }
  }
  
  return lines.join('\n');
}

function generateIndex(report: DocgenReport & { totalFiles?: number; totalLines?: number }): string {
  return `# API Documentation

## Project: ProjectMind

## Modules

${report.modules.map(m => `- [${m.path}](${m.path.replace(/[^a-zA-Z0-9]/g, '-')}.md) (${m.fileCount} files)`).join('\n')}

## Summary

- Total Files: ${report.totalFiles ?? 'N/A'}
- Total Lines: ${report.totalLines ?? 'N/A'}
- Languages: ${Object.keys(report.languages).join(', ')}

---
*Generated by ProjectMind*
`;
}